(source "melpa" "http://melpa.org/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "ahk-mode")
(depends-on "ansible")
(depends-on "ansible-doc")
(depends-on "ansible-vault")
(depends-on "ant")
(depends-on "apache-mode")
(depends-on "blank-mode")
(depends-on "bundler")
(depends-on "cask-mode")
(depends-on "chef-mode")
(depends-on "cl")
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "color-theme-solarized")
(depends-on "crontab-mode")
(depends-on "csharp-mode")
(depends-on "csv-mode")
(depends-on "ctags")
(depends-on "cython-mode")
(depends-on "decide")
; (depends-on "deferred")
(depends-on "diffview")
(depends-on "dockerfile-mode")
(depends-on "fountain-mode")
(depends-on "elfeed")
(depends-on "elisp-format")
(depends-on "elisp-lint")
(depends-on "encourage-mode")
(depends-on "ess")
;; Evaluated up to F
(depends-on "go-mode")
(depends-on "golint")
(depends-on "gradle-mode")
(depends-on "julia-mode")
(depends-on "julia-shell")
(depends-on "imenu-list")
(depends-on "magit")
(depends-on "olivetti")
(depends-on "pandoc-mode")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "powershell")
(depends-on "puppet-mode")
(depends-on "rainbow-delimiters")
(depends-on "rake")
(depends-on "scss-mode")
(depends-on "textile-mode")
(depends-on "use-package")
(depends-on "tuareg")
(depends-on "vlf")
(depends-on "yaml-mode")

;; Themes
(depends-on "noctilux-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "molokai-theme")
