(source "melpa" "http://melpa.org/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "ahk-mode")
(depends-on "cl")
(depends-on "chef-mode")
(depends-on "color-theme-solarized")
(depends-on "fountain-mode")
(depends-on "go-mode")
(depends-on "golint")
(depends-on "gradle-mode")
(depends-on "julia-mode")
(depends-on "julia-shell")
(depends-on "imenu-list")
(depends-on "magit")
(depends-on "olivetti")
(depends-on "pandoc-mode")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "powershell")
(depends-on "puppet-mode")
(depends-on "rainbow-delimiters")
(depends-on "rake")
(depends-on "scss-mode")
(depends-on "textile-mode")
(depends-on "use-package")
(depends-on "tuareg")
(depends-on "vlf")
(depends-on "yaml-mode")

;; Themes
(depends-on "noctilux-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "molokai-theme")